server:
  port: 8080
  error:
    whitelabel:
      enabled: false

spring:
  profiles:
    active: test
  main:
    allow-bean-definition-overriding: true
    banner-mode: "off"
  thymeleaf:
    cache: false
    check-template: true
    check-template-location: true
    enabled: true
    encoding: UTF-8
    # excluded-view-names:
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html
    # template-resolver-order:
    # view-names:
    servlet:
      content-type: text/html
  datasource:
    # h2 database
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:iwa_test
    username: sa
    password: password
    initialization-mode: always
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hiberate:
        format_sql: true
        # h2 database dialect
        dialect: org.hibernate.dialect.H2Dialect
  mvc:
    favicon:
      enabled: false
    throw-exception-if-no-handler-found: true
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

logging:
  level:
    root: WARN
    com.microfocus: DEBUG
    org.springframework.web: INFO
    org.springframework.security: INFO

app:
  name: IWA Pharmacy Direct
  version: 1.0
  currency: GBP
  invalidPasswordList: "/invalid-password-list.txt"
  data:
    page-size: 25
  messages:
    home: Welcome to our site!
  jwt:
    secret: iwaSecretKey
    expiration-ms: 86400000
    refresh-ms: 86400000
