server:
  port: 8080
  error:
    whitelabel:
      enabled: false
  servlet:
    context-path: /

spring:
  profiles:
    active: prod
  main:
    allow-bean-definition-overriding: true
    banner-mode: "off"
  thymeleaf:
    cache: false
    check-template: true
    check-template-location: true
    enabled: true
    encoding: UTF-8
    # excluded-view-names:
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html
    # template-resolver-order:
    # view-names:
    servlet:
      content-type: text/html
  datasource:
    # h2 database
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:iwa
    username: sa
    password: password
    initialization-mode: always
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hiberate:
        # h2 database dialect
        dialect: org.hibernate.dialect.H2Dialect
  mvc:
#    favicon:
#      enabled: false
    throw-exception-if-no-handler-found: true
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

#  resources:
#    add-mappings: false


springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
#    url: /v3/api-docs
    path: /swagger-ui.html
    display-request-duration: true

 #   groups-order: DESC
    disable-swagger-default-url: true
  paths-to-match: /api/**
#  group-configs:
#    - group: application
#      paths-to-match: /api/**
#    - group: actuator
#      paths-to-match: /actuator/**


logging:
  level:
    root: WARN
    com.microfocus: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO

app:
  name: IWA Pharmacy Direct
  version: 1.0
  currency: GBP
  invalidPasswordList: "/invalid-password-list.txt"
  data:
    page-size: 25
  messages:
    home: Welcome to our site!
  jwt:
    secret: iwaSecretKey
    expiration-ms: 86400000
    refresh-ms: 86400000
